issem/urls.py
# coding:utf-8
from django.conf.urls import url
from django.views.generic import TemplateView
from issem import views
from issem.views import *
from issem.views.cruds.procedimentos_medicos import BuscaProcedimentosMedicosView

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^logout', 'django.contrib.auth.views.logout', {'next_page': '/issem/login/'}, name='logout'),
    url(r'^primeiro_login/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', VerificaTokenPrimeiroLoginSegurado, name='user-activation-link'),
    url(r'^escolha_papel/', views.escolha_papel, name='escolha_papel'),

    # PAINÉIS
    url(r'^funcionario/$', PaginaFuncionarioView.as_view(), name='funcionario'),
    url(r'^medico/$', PaginaMedicoView.as_view(), name='medico'),
    url(r'^segurado$', PaginaSeguradoView.as_view(), name='segurado'),

    # CID
    url(r'^cad/cid/$', CidView.as_view(), name='cad_cid'),
    url(r'^edita/cid/(?P<id>\d+)/$', CidView.as_view(), name='edita_cid'),
    url(r'^deleta/cid/(?P<id>[0-9]+)/$', CidView.CidDelete, name='deleta_cid'),
    url(r'^lista/cids/$', CidView.ListaCids, name='lista_cids'),
    url(r'^campo/lista/?$', CidView.ListaCids, name='campo_pesquisa_cids'),

    # BENEFÍCIO
    url(r'^cad/beneficio/$', BeneficioView.as_view(), name='cad_beneficio'),
    url(r'^edita/beneficio/(?P<id>\d+)/$', BeneficioView.as_view(), name='edita_beneficio'),
    url(r'^deleta/beneficio/(?P<id>[0-9]+)/$', BeneficioView.BeneficioDelete, name='deleta_beneficio'),
    url(r'^lista/beneficios/$', BeneficioView.ListaBeneficios, name='lista_beneficios'),

    # PROCEDIMENTO MÉDICO
    url(r'^cad/procedimento_medico/$', ProcedimentoMedicoView.as_view(), name='cad_procedimento_medico'),
    url(r'^edita/procedimento_medico/(?P<id>\d+)/$', ProcedimentoMedicoView.as_view(),
        name='edita_procedimento_medico'),
    url(r'^deleta/procedimento_medico/(?P<id>[0-9]+)/$', ProcedimentoMedicoView.ProcedimentoMedicoDelete,
        name='deleta_procedimento_medico'),
    url(r'^lista/procedimentos_medicos/$', ProcedimentoMedicoView.ListaProcedimentosMedicos,
        name='lista_procedimentos_medicos'),

    # FUNÇÃO
    url(r'^cad/funcao/$', FuncaoView.as_view(), name='cad_funcao'),
    url(r'^edita/funcao/(?P<id>\d+)/$', FuncaoView.as_view(), name='edita_funcao'),
    url(r'^deleta/funcao/(?P<id>[0-9]+)/$', FuncaoView.FuncaoDelete, name='deleta_funcao'),

    # CARGO
    url(r'^cad/cargo/$', CargoView.as_view(), name='cad_cargo'),
    url(r'^edita/cargo/(?P<id>\d+)/$', CargoView.as_view(), name='edita_cargo'),
    url(r'^deleta/cargo/(?P<id>[0-9]+)/$', CargoView.CargoDelete, name='deleta_cargo'),
    url(r'^atualiza/cargo/$', CargoView.AtualizaCargo, name='atualiza_cargo'),

    # TIPO DEPENDENTE
    url(r'^cad/tipo_dependente/$', TipoDependenteView.as_view(), name='cad_tipo_dependente'),
    url(r'^edita/tipo_dependente/(?P<id>\d+)/$', TipoDependenteView.as_view(), name='edita_tipo_dependente'),
    url(r'^deleta/tipo_dependente/(?P<id>[0-9]+)/$', TipoDependenteView.TipoDependenteDelete,
        name='deleta_tipo_dependente'),

    # TIPO EXAME
    url(r'^cad/tipo_exame/$', TipoExameView.as_view(), name='cad_tipo_exame'),
    url(r'^edita/tipo_exame/(?P<id>\d+)/$', TipoExameView.as_view(), name='edita_tipo_exame'),
    url(r'^deleta/tipo_exame/(?P<id>[0-9]+)/$', TipoExameView.TipoExameDelete, name='deleta_tipo_exame'),

    # SECRETARIA
    url(r'^cad/secretaria/$', SecretariaView.as_view(), name='cad_secretaria'),
    url(r'^edita/secretaria/(?P<id>\d+)/$', SecretariaView.as_view(), name='edita_secretaria'),
    url(r'^deleta/secretaria/(?P<id>[0-9]+)/$', SecretariaView.SecretariaDelete, name='deleta_secretaria'),
    url(r'^atualiza/secretaria/$', SecretariaView.AtualizaSecretaria, name='atualiza_secretaria'),

    # LOCAL DE TRABALHO
    url(r'^cad/local_trabalho/$', LocalTrabalhoView.as_view(), name='cad_local_trabalho'),
    url(r'^edita/local_trabalho/(?P<id>\d+)/$', LocalTrabalhoView.as_view(), name='edita_local_trabalho'),
    url(r'^deleta/local_trabalho/(?P<id>[0-9]+)/$', LocalTrabalhoView.LocalTrabalhoDelete,
        name='deleta_local_trabalho'),
    url(r'^atualiza/local_trabalho/$', LocalTrabalhoView.AtualizaLocalTrabalho, name='atualiza_local_trabalho'),

    # DEPENDENTE
    url(r'^cad/dependente/$', DependenteView.as_view(), name='cad_dependente'),
    url(r'^cad/dependente_segurado/(?P<id_segurado>\d+)/$', DependenteView.as_view(), name='cad_dependente_segurado'),
    url(r'^edita/dependente/(?P<id>\d+)/$', DependenteView.as_view(), name='edita_dependente'),
    url(r'^deleta/dependente/(?P<id>[0-9]+)/$', DependenteView.DependenteDelete, name='deleta_dependente'),
    url(r'^ativa/dependente/(?P<id>[0-9]+)/$', DependenteView.AtivaDelete, name='ativa_dependente'),
    url(r'^lista/dependentes/$', DependenteView.ListaDependentes, name='lista_dependentes'),
    url(r'^lista/dependentes/inativos/$', DependenteView.ListaDependentesInativos, name='lista_dependentes_inativos'),
    url(r'^transferencia/$', TransferenciaSegurado.as_view(), name='transferencia'),
    url(r'^busca_segurado/(?P<id>\d+)/$', TransferenciaSegurado.as_view(), name='seleciona_segurado'),

    # SEGURADO
    url(r'^cad/segurado/$', SeguradoView.as_view(), name='cad_segurado'),
    url(r'^edita/segurado/(?P<id>\d+)/$', SeguradoView.as_view(), name='edita_segurado'),
    url(r'^deleta/segurado/(?P<id>[0-9]+)/$', SeguradoView.SeguradoDelete, name='deleta_segurado'),
    url(r'^ativa/segurado/(?P<id>[0-9]+)/$', SeguradoView.SeguradoAtiva, name='ativa_segurado'),
    url(r'^lista/segurados/$', SeguradoView.ListaSegurados, name='lista_segurados'),
    url(r'^lista/segurados/inativos/$', SeguradoView.ListaSeguradosInativos, name='lista_segurados_inativos'),
    url(r'^lista/requerimentos/segurado/(?P<id>[0-9]+)/$', views.ListaRequerimentosSegurado,
        name='requerimentos_segurado'),

    # SERVIDOR
    url(r'^cad/servidor/$', ServidorView.as_view(), name='cad_servidor'),
    url(r'^edita/servidor/(?P<id>\d+)/$', ServidorView.as_view(), name='edita_servidor'),
    url(r'^deleta/servidor/(?P<id>[0-9]+)/$', ServidorView.ServidorDelete, name='deleta_servidor'),
    url(r'^ativa/servidor/(?P<id>[0-9]+)/$', ServidorView.ServidorAtiva, name='ativa_servidor'),
    url(r'^lista/servidores/$', ServidorView.ListaServidores, name='lista_servidores'),
    url(r'^lista/servidores/inativos/$', ServidorView.ListaServidoresInativos, name='lista_servidores_inativos'),

    # SEGURADO / SERVIDOR
    url(r'^edita/senha/(?P<id>\d+)/(?P<id_group>\d+)/$', EditaSenhaView.as_view(), name='edita_senha'),

    # CIDADE / ESTADO
    url(r'^escolha_cidade_atual/$', CidadeView.as_view(), name='escolha_cidade_atual'),
    url(r'^escolha_cidade_natural/$', CidadeView.as_view(), name='escolha_cidade_natural'),
    url(r'^escolha_cidade_local_trabalho/$', CidadeView.as_view(), name='escolha_cidade_local_trabalho'),

    # CONSULTA PARÂMETROS
    url(r'^edita/parametros_consulta/$', ParametrosConfiguracaoView.as_view(),
        name='edita_parametros_consulta'),

    # REQUERIMENTO / AGENDAMENTO
    url(r'^cad/requerimento/(?P<id_beneficio>\d+)/$', RequerimentoView.as_view(), name='cad_requerimento'),
    url(r'^cad/requerimento_servidor/(?P<id_beneficio>\d+)/$', RequerimentoServidorView.as_view(),
        name='cad_requerimento_servidor'),
    url(r'^edita/requerimento/servidor/(?P<id_requerimento>\d+)/(?P<id_agendamento>\d+)/$',
        RequerimentoServidorView.as_view(), name='edita_requerimento'),
    url(r'^deleta/requerimento/(?P<id_requerimento>[0-9]+)/(?P<id_agendamento>[0-9]+)/$',
        views.RequerimentoAgendamentoDelete, name='deleta_requerimento'),
    url(r'^deleta/requerimento_sem_agendamento/(?P<id>[0-9]+)/$',
        views.RequerimentoSemAgendamentoDelete, name='deleta_requerimento_sem_agendamento'),
    url(r'^gera/agendamento/(?P<id_requerimento>\d+)/$', GeraAgendamentoServidorView.as_view(),
        name='define_agendamento'),
    url(r'^agenda/$', views.ApresentaAgendamentos, name='tabela_agendamentos'),
    url(r'^agenda/requerimentos/sem/agendamento$', views.ApresentaRequerimentosSemAgendamento,
        name='tabela_agendamentos_sem_requerimento'),
    url(r'^agenda/medica/$', views.ApresentaAgendamentosMedico, name='agenda_medica'),
    url(r'^agenda/medica/filtro/$', views.ApresentaAgendamentosMedico, name='filtro_agenda'),
    url(r'^requerimentos_sem_agendamento/$', views.ApresentaRequerimentosSemAgendamento,
        name='tabela_requerimentos_sem_agendamento'),
    url(r'^comprovante_agendamento/pdf/(?P<id_agendamento>\d+)/(?P<id_usuario>\d+)/$',
        views.GeraComprovanteAgendamento, name='comprovante_agendamento'),
    url(r'^pagina_requerimento/(?P<id>\d+)/$', views.VisualizarRequerimento, name='visualizar_requerimento'),
    url(r'^pagina_requerimento_sem_agendamento/(?P<id>\d+)/$', views.VisualizarRequerimentoSemAgendamento,
        name='visualizar_requerimento_sem_agendamento'),

    # LAUDO
    url(r'^laudo/(?P<id>\d+)/$', LaudoView.VisualizarLaudo, name='visualizar_laudo'),
    url(r'^cad/laudo/$', LaudoView.as_view(), name='cad_laudo'),
    url(r'^lista/laudos/$', LaudoView.ListaLaudos, name='lista_laudos'),
    url(r'^laudo/adendo/(?P<id>\d+)/$', LaudoView.AdicionarAdendo, name='adicionar_adendo'),
    url(r'^busca_procedimentos_medicos/$', BuscaProcedimentosMedicosView.as_view(), name='busca_procedimentos_medicos'),

    # CONTATO ISSEM
    url(r'^cad/contato_issem/$', ContatoIssemView.as_view(), name='cad_contato_issem'),
    url(r'^edita/contato_issem/(?P<id>\d+)/$', ContatoIssemView.as_view(), name='edita_contato_issem'),
    url(r'^deleta/contato_issem/(?P<id>[0-9]+)/$', ContatoIssemView.ContatoIssemDelete, name='deleta_contato_issem'),
    url(r'^lista/contatos/$', ContatoIssemView.ListaContatosIssem, name='lista_contatos_issem'),

    # PERFIL

issem_project/urls.py
# coding:utf-8
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from issem import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^issem/', include('issem.urls', namespace="issem")),
    url(r'^tinymce/', include('tinymce.urls')),

    # ALTERAÇÃO DE SENHA
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'password_reset/password_reset_form.html',
                                                          'email_template_name': 'password_reset/password_reset_email.html',
                                                          'subject_template_name': 'password_reset/password_reset_subject.txt'},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'password_reset/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'password_reset/password_reset_complete.html'}, name='password_reset_complete'),

]

issem/models/adendo.py
# coding:utf-8
from django.db import models


class AdendoModel(models.Model):
    descricao = models.CharField(max_length=1000)
    data = models.DateField()

    def __unicode__(self):
        return self.descricao

    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = "Adendo"
        verbose_name_plural = "Adendos"

issem/models/agendamento.py
# coding:utf-8
from django.db import models
from issem.models.requerimento import RequerimentoModel
from datetime import datetime


class AgendamentoModel(models.Model):
    data_agendamento = models.DateField(blank=True, null=True)
    data_pericia = models.DateField(blank=True, null=True)
    hora_pericia = models.TimeField()
    requerimento = models.ForeignKey(RequerimentoModel, null=True, blank=True)

    def __unicode__(self):
        return str(datetime.combine(self.data_pericia, self.hora_pericia)) +str(" ID Requerimento:") + str(self.requerimento.id)

    def __str__(self):
        return str(datetime.combine(self.data_pericia, self.hora_pericia)) +str(" ID Requerimento:") + str(self.requerimento.id)

    class Meta:
        verbose_name = "Agendamento"
        verbose_name_plural = "Agendamentos"

issem/models/beneficio.py
# coding:utf-8
from django.db import models


class BeneficioModel(models.Model):
    concessao = models.BooleanField(default=False)
    data_inicial = models.DateField()
    data_final = models.DateField()
    data_retorno = models.DateField()
    data_pericia = models.DateField()
    descricao = models.CharField(max_length=1000)
    numero_portaria = models.CharField(max_length=128)
    data_portaria = models.DateField()
    salario_maximo = models.CharField(max_length=128)
    observacao = models.CharField(max_length=1000)
    carencia = models.CharField(max_length=1000)
    excluido = models.BooleanField(default=False)

    def __unicode__(self):
        return self.descricao

    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = "Benefício"
        verbose_name_plural = "Benefícios"

issem/models/cargo.py
# coding:utf-8
from django.db import models


class CargoModel(models.Model):
    nome = models.CharField(max_length=128, null=False)
    excluido = models.BooleanField(default=False)

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Cargo"
        verbose_name_plural = "Cargos"

issem/models/cid.py
# coding:utf-8
from django.db import models


class CidModel(models.Model):
    descricao = models.CharField(max_length=128, null=False)
    status = models.BooleanField(default=False)
    gravidade = models.BooleanField(default=False)
    cod_cid = models.CharField(max_length=128)
    excluido = models.BooleanField(default=False)

    def __unicode__(self):
        return self.descricao

    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = "CID"
        verbose_name_plural = "CIDs"

issem/models/cidade.py
# coding:utf-8
from django.db import models
from issem.models.estado import EstadoModel


class CidadeModel(models.Model):
    nome = models.CharField(max_length=128, null=False)
    uf = models.ForeignKey(EstadoModel)

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Cidade"
        verbose_name_plural = "Cidades"

issem/models/consulta_parametros.py
# coding: utf-8
from django.db import models


class ConsultaParametrosModel(models.Model):
    tempo_consulta = models.IntegerField(null=False)
    tempo_espera = models.IntegerField(null=False)
    inicio_atendimento = models.TimeField()
    limite_consultas = models.IntegerField(null=False)
    gap_agendamento = models.IntegerField()

    def __unicode__(self):
        return "Parâmetro de consulta" + str(self.id)

    def __str__(self):
        return "Parâmetro de consulta" + str(self.id)

    class Meta:
        verbose_name = "Consulta Parâmetro"
        verbose_name_plural = "Consulta Parâmetros"

issem/models/consultasparametros.py
# coding:utf-8
from django.db import models

class ConsultasParametrosModel(models.Model):
    tempo_consulta = models.IntegerField(null=False)
    tempo_espera = models.IntegerField(null=False)
    inicio_atendimento = models.TimeField(null=False)
    limite_consultas = models.IntegerField(null=False)

    def __unicode__(self):
        return self.tempo_consulta

    def __str__(self):
        return self.tempo_consulta

    class Meta:
        verbose_name = "Consulta Parâmetro"
        verbose_name_plural = "Consultas Parâmetros"

issem/models/contato_issem.py
# coding: utf-8
from django.db import models


class ContatoIssemModel(models.Model):
    nome = models.CharField(max_length=128, blank=True)
    cargo = models.CharField(max_length=128, blank=True)
    departamento = models.CharField(max_length=128, blank=True)
    telefone = models.CharField(max_length=15)
    email = models.EmailField(blank=True)

    def __unicode__(self):
        return "Contato ISSEM" + str(self.id)

    def __str__(self):
        return "Contato ISSEM" + str(self.id)

    class Meta:
        verbose_name = "Contato ISSEM"
        verbose_name_plural = "Contatos ISSEM"

issem/models/contatos_issem.py
# coding: utf-8
from django.db import models
from issem.models.cargo import CargoModel


class ContatoIssemModel(models.Model):
    telefone = models.CharField(max_length=15)
    email = models.EmailField()
    descricao = models.CharField(max_length=128)
    cargo = models.ForeignKey(CargoModel, null=True, blank=True)

    def __unicode__(self):
        return "Contato ISSEM" + str(self.id)

    def __str__(self):
        return "Contato ISSEM" + str(self.id)

    class Meta:
        verbose_name = "Contato ISSEM"
        verbose_name_plural = "Contatos ISSEM"

issem/models/dependente.py
# coding:utf-8
from django.db import models
from issem.models.pessoa import PessoaModel
from issem.models.tipo_dependente import TipoDependenteModel


class DependenteModel(PessoaModel):
    tipo = models.ForeignKey(TipoDependenteModel, null=False, blank=False)
    data_inicial = models.DateField(null=True, blank=True)
    data_final = models.DateField(null=True, blank=True)

    def __unicode__(self):
        return self.get_full_name()

    def __str__(self):
        return self.get_full_name()

    class Meta:
        verbose_name = "Dependente"
        verbose_name_plural = "Dependentes"

issem/templates/listas/segurados.html
{% extends 'base.html' %}

{% block body_block %}

    <div class="ui centered grid issem-grid">
        <div class="ui row segment issem-segment issem-segment-border">

            {% if msg %}
                <div class="sixteen wide column issem-div-message">
                    <div class="ui {{ tipo_msg }} message">
                        <div class="header">
                            {{ msg }}
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="three wide column">
                <a href="{% url 'issem:funcionario' %}">
                    <div class="ui labeled icon button basic">
                        <i class="left arrow icon"></i> Voltar
                    </div>
                </a>
            </div>

            <div class="ten wide column">
                <div class="issem-title-edit-page">
                    <h1><i class="group icon"></i> Segurados</h1>
                </div>
            </div>

            <div class="three wide column">
                <div class="ui right floated {% if request.session.administrador %}vertical{% endif %} buttons">
                    <a href="{% url 'issem:cad_segurado' %}"
                       class="ui labeled icon button green">
                        <i class="plus icon"></i> Adicionar Novo
                    </a>
                    {% if request.session.administrador %}
                        <a href="{% url 'issem:lista_segurados_inativos' %}"
                           class="ui labeled icon button red">
                            <i class="trash icon"></i> Excluídos
                        </a>
                    {% endif %}
                </div>
            </div>

            <div class="ui centered row">
                <br/>
                <form class="ui form" id="CampoFiltroForm" method="get" action="{% url 'issem:lista_segurados' %}">
                    <div class="ui right aligned category search">
                        <div class="ui icon input">
                            <i class="search icon"></i>
                            <input type="text" id="id_campo" name="filtro" placeholder="Pesquisar">
                        </div>
                    </div>
                </form>
            </div>

            {% if dados %}
                <table class="ui celled table issem-table-form">
                    <thead>
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Email</th>
                        <th class="ui right aligned">AÇÕES <i class="setting icon"></i>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for dado in dados %}
                        <tr>
                            {% if dado.get_full_name != "" %}
                                <td>
                                    <a href="{% url 'issem:perfil' dado.id %}">{{ dado.get_full_name }}</a>
                                </td>
                            {% else %}
                                <td>---</td>
                            {% endif %}
                            {% if dado.cpf != "" %}
                                <td>{{ dado.cpf }}</td>
                            {% else %}
                                <td>---</td>
                            {% endif %}
                            {% if dado.email != "" %}
                                <td>{{ dado.email }}</td>
                            {% else %}
                                <td>---</td>
                            {% endif %}

                            <td>
                                <div class="ui right floated {% if request.session.administrador %}vertical{% endif %} buttons">
                                    {% if request.session.administrador %}
                                        <a href="{% url 'issem:grupo' dado.id %}" class="ui labeled icon button blue">
                                            <i class="exchange icon"></i> Transferência de Grupo
                                        </a>
                                    {% endif %}
                                    {% if usuario_logado.id == dado.id or request.session.administrador %}
                                        <a href="{% url 'issem:edita_segurado' dado.id %}"
                                           class="ui labeled icon button ">
                                            <i class="edit icon"></i> Editar
                                        </a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                </table>

                {% include 'blocos/pagination.html' %}
            {% else %}
                <div class="sixteen wide column issem-div-message">
                    <br/>
                    <div class="ui yellow message">
                        <div class="header">
                            Não existem dados cadastrados
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

issem/templates/listas/servidores.html
{% extends 'base.html' %}

{% block body_block %}

    <div class="ui centered grid issem-grid">
        <div class="ui row segment issem-segment issem-segment-border">

            {% if msg %}
                <div class="sixteen wide column issem-div-message">
                    <div class="ui {{ tipo_msg }} message">
                        <div class="header">
                            {{ msg }}
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="three wide column">
                <a href="{% url 'issem:funcionario' %}">
                    <div class="ui labeled icon button basic">
                        <i class="left arrow icon"></i> Voltar
                    </div>
                </a>
            </div>

            <div class="ten wide column">
                <div class="issem-title-edit-page">
                    <h1><i class="group icon"></i> Servidores</h1>
                </div>
            </div>

            <div class="three wide column">
                <div class="ui right floated {% if request.session.administrador %}vertical{% endif %} buttons">
                    <a href="{% url 'issem:cad_servidor' %}"
                       class="ui labeled icon button green">
                        <i class="plus icon"></i> Adicionar Novo
                    </a>
                    {% if request.session.administrador %}
                        <a href="{% url 'issem:lista_servidores_inativos' %}"
                           class="ui labeled icon button red">
                            <i class="trash icon"></i> Excluídos
                        </a>
                    {% endif %}
                </div>
            </div>

            <div class="ui centered row">
                <br/>
                <form class="ui form" id="CampoFiltroForm" method="get" action="{% url 'issem:lista_servidores' %}">
                    <div class="ui right aligned category search">
                        <div class="ui icon input">
                            <i class="search icon"></i>
                            <input type="text" id="id_campo" name="filtro" placeholder="Pesquisar">
                        </div>
                    </div>
                </form>
            </div>

            {% if dados %}
                <table class="ui celled table issem-table-form">
                    <thead>
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Email</th>
                        <th width="330">
                            Departamento
                            <form id="form_lista_servidores" class="ui form issem-form-filter-group"
                                  action="{% url 'issem:lista_servidores' %}" method="post">
                                {% csrf_token %}
                                <select onchange="this.form.submit()" id="filtro_grupo" name="filtro_grupo">
                                    <option value="">Selecione um grupo</option>
                                    <option value="todos"
                                            {% if grupo_controle == "todos" %}selected="selected"{% endif %}>Todos
                                    </option>
                                    <option value="administrativo"
                                            {% if grupo_controle == "administrativo" %}selected="selected"{% endif %}>
                                        Administrativo
                                    </option>
                                    <option value="tecnico"
                                            {% if grupo_controle == "tecnico" %}selected="selected"{% endif %}>Técnico
                                    </option>
                                </select>
                            </form>
                        </th>
                        <th class="ui right aligned">AÇÕES <i class="setting icon"></i>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for dado in dados %}
                        <tr>
                            {% if dado.get_full_name != "" %}
                                <td>
                                    <a href="{% url 'issem:perfil' dado.id %}">{{ dado.get_full_name }}</a>
                                </td>
                            {% else %}
                                <td>---</td>
                            {% endif %}
                            {% if dado.cpf != "" %}
                                <td>{{ dado.cpf }}</td>
                            {% else %}
                                <td>---</td>
                            {% endif %}
                            {% if dado.email != "" %}
                                <td>{{ dado.email }}</td>
                            {% else %}
                                <td>---</td>
                            {% endif %}
                            {% if dado.groups.all != "" %}
                                <td>
                                    {% for grupo in dado.groups.all %}
                                        {{ grupo }};
                                    {% endfor %}
                                </td>
                            {% else %}
                                <td>---</td>
                            {% endif %}
                            <td>
                                <div class="ui right floated {% if request.session.administrador %}vertical{% endif %} buttons">
                                    {% if request.session.administrador %}
                                        <a href="{% url 'issem:grupo' dado.id %}" class="ui labeled icon button blue">
                                            <i class="exchange icon"></i> Transferência de Grupo
                                        </a>
                                    {% endif %}
                                    {% if usuario_logado.id == dado.id or request.session.administrador %}
                                        <a href="{% url 'issem:edita_servidor' dado.id %}"
                                           class="ui labeled icon button ">
                                            <i class="edit icon"></i> Editar
                                        </a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                </table>

                {% include 'blocos/pagination.html' %}
            {% else %}
                <div class="sixteen wide column issem-div-message">
                    <br/>
                    <div class="ui yellow message">
                        <div class="header">
                            Não existem dados cadastrados
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}